"""
# apiwx - A generic definitions for wxPython paint tool.
"""


from wx import (
    PaintDC,
    Pen,
    BRUSHSTYLE_BDIAGONAL_HATCH,
    BRUSHSTYLE_CROSS_HATCH,
    BRUSHSTYLE_FDIAGONAL_HATCH,
    BRUSHSTYLE_HORIZONTAL_HATCH,
    BRUSHSTYLE_VERTICAL_HATCH,
    BRUSHSTYLE_CROSSDIAG_HATCH,
    BRUSHSTYLE_SOLID,
    BRUSHSTYLE_FIRST_HATCH,
    BRUSHSTYLE_LAST_HATCH,
    BRUSHSTYLE_STIPPLE_MASK_OPAQUE,
    BRUSHSTYLE_STIPPLE_MASK,
    BRUSHSTYLE_STIPPLE,
    TRANSPARENT_BRUSH,
)

