# Batch import of wxPython major flag constants
from wx import (
	DEFAULT_FRAME_STYLE, HSCROLL, VSCROLL, LC_REPORT,
	SL_HORIZONTAL, GA_HORIZONTAL,
	SIMPLE_BORDER, SUNKEN_BORDER, RAISED_BORDER, NO_BORDER,
	TAB_TRAVERSAL, WANTS_CHARS,
	WS_EX_VALIDATE_RECURSIVELY, WS_EX_BLOCK_EVENTS, WS_EX_TRANSIENT, WS_EX_PROCESS_IDLE, WS_EX_PROCESS_UI_UPDATES,
	FRAME_SHAPED, FRAME_TOOL_WINDOW, FRAME_NO_TASKBAR, FRAME_FLOAT_ON_PARENT,
	DEFAULT_DIALOG_STYLE, RESIZE_BORDER, DIALOG_NO_PARENT, DIALOG_EX_METAL,
	BORDER_NONE, BORDER_SIMPLE, BORDER_SUNKEN, BORDER_RAISED, BORDER_STATIC, BORDER_THEME,
	FULLSCREEN_NOMENUBAR, FULLSCREEN_NOTOOLBAR, FULLSCREEN_NOSTATUSBAR, FULLSCREEN_NOBORDER, FULLSCREEN_NOCAPTION, FULLSCREEN_ALL
)

# Window/Frame styles
class WindowStyle:
	DEFAULT_FRAME_STYLE = DEFAULT_FRAME_STYLE
	HSCROLL = HSCROLL
	VSCROLL = VSCROLL
	LC_REPORT = LC_REPORT

# Control styles
class ControlStyle:
	SL_HORIZONTAL = SL_HORIZONTAL
	GA_HORIZONTAL = GA_HORIZONTAL

# Border styles
class BorderStyle:
	SIMPLE = SIMPLE_BORDER
	SUNKEN = SUNKEN_BORDER
	RAISED = RAISED_BORDER
	NONE = NO_BORDER

# Traversal styles
class TraversalStyle:
	TAB_TRAVERSAL = TAB_TRAVERSAL
	WANTS_CHARS = WANTS_CHARS

# Extra window styles
class ExtraWindowStyle:
	VALIDATE_RECURSIVELY = WS_EX_VALIDATE_RECURSIVELY
	BLOCK_EVENTS = WS_EX_BLOCK_EVENTS
	TRANSIENT = WS_EX_TRANSIENT
	PROCESS_IDLE = WS_EX_PROCESS_IDLE
	PROCESS_UI_UPDATES = WS_EX_PROCESS_UI_UPDATES

# Frame styles
class FrameStyle:
	FRAME_SHAPED = FRAME_SHAPED
	FRAME_TOOL_WINDOW = FRAME_TOOL_WINDOW
	FRAME_NO_TASKBAR = FRAME_NO_TASKBAR
	FRAME_FLOAT_ON_PARENT = FRAME_FLOAT_ON_PARENT

# Dialog styles
class DialogStyle:
	DEFAULT_DIALOG_STYLE = DEFAULT_DIALOG_STYLE
	RESIZE_BORDER = RESIZE_BORDER
	DIALOG_NO_PARENT = DIALOG_NO_PARENT
	DIALOG_EX_METAL = DIALOG_EX_METAL

# Control border styles
class ControlBorderStyle:
	NONE = BORDER_NONE
	SIMPLE = BORDER_SIMPLE
	SUNKEN = BORDER_SUNKEN
	RAISED = BORDER_RAISED
	STATIC = BORDER_STATIC
	THEME = BORDER_THEME

# Miscellaneous flags
class MiscFlag:
	FULLSCREEN_NOMENUBAR = FULLSCREEN_NOMENUBAR
	FULLSCREEN_NOTOOLBAR = FULLSCREEN_NOTOOLBAR
	FULLSCREEN_NOSTATUSBAR = FULLSCREEN_NOSTATUSBAR
	FULLSCREEN_NOBORDER = FULLSCREEN_NOBORDER
	FULLSCREEN_NOCAPTION = FULLSCREEN_NOCAPTION
	FULLSCREEN_ALL = FULLSCREEN_ALL
